Fix. failed `heroku run rake` command
https://circleci.com/gh/sue445/sebastian-badge/412

heroku run rake ar:migrate --app $HEROKU_APP_NAME
Running rake ar:migrate on ⬢ sebastian-badge... starting, run.5082 (Free)
Running rake ar:migrate on ⬢ sebastian-badge... connecting, run.5082 (Free)
Running rake ar:migrate on ⬢ sebastian-badge... up, run.5082 (Free)
rake aborted!
Gem::LoadError: You have already activated rake 12.0.0, but your Gemfile requires rake 11.3.0. Prepending `bundle exec` to your command may solve this.

/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:40:in `block in setup'
/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:25:in `map'

/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.6/lib/bundler/runtime.rb:25:in `setup'

/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'

/app/vendor/bundle/ruby/2.4.0/gems/bundler-1.13.6/lib/bundler/setup.rb:10:in `<top (required)>'

/app/Rakefile:1:in `<top (required)>'

LoadError: cannot load such file -- bundler/setup
/app/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)