Add haml
```
bundle exec rake ar:migrate:reset
rake aborted!
LoadError: cannot load such file -- haml
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/haml.rb:2:in `require'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/haml.rb:2:in `<top (required)>'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:243:in `require'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:243:in `block in lazy_load'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:241:in `each'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:241:in `lazy_load'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:216:in `lookup'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt/mapping.rb:154:in `[]'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/tilt-2.0.7/lib/tilt.rb:53:in `template_for'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:5:in `<module:OutputHelpers>'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:3:in `<module:Helpers>'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:2:in `<module:Padrino>'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers/output_helpers/haml_handler.rb:1:in `<top (required)>'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `require'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `block in glob_require'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `block in glob'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `each'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:14:in `glob'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-support-0.14.1/lib/padrino-support/file_set.rb:23:in `glob_require'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-helpers-0.14.1/lib/padrino-helpers.rb:9:in `<top (required)>'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-0.14.1/lib/padrino.rb:4:in `require'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-0.14.1/lib/padrino.rb:4:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/home/ubuntu/sebastian-badge/config/boot.rb:8:in `<top (required)>'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-core-0.14.1/lib/padrino-core/cli/rake_tasks.rb:15:in `require'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-core-0.14.1/lib/padrino-core/cli/rake_tasks.rb:15:in `block in <top (required)>'
/home/ubuntu/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/bin/bundle:22:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/bin/bundle:22:in `<main>'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `eval'
/home/ubuntu/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => ar:migrate:reset => ar:drop => skeleton
(See full trace by running task with --trace)
```